# Generated by Django 4.2.6 on 2023-10-27 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0002_auto_20231021_1353'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordernborrow', '0004_alter_borrowedbook_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booklist.buku')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
