# Generated by Django 4.2.6 on 2023-11-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordernborrow', '0006_remove_borrowedhistory_borrowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
