# Generated by Django 4.2.6 on 2023-11-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordernborrow', '0007_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='food_price',
            new_name='price',
        ),
    ]
