# Generated by Django 4.2.6 on 2023-11-27 09:43

from django.db import migrations
from django.core.management import call_command

def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "food.json")


class Migration(migrations.Migration):

    dependencies = [
        ('ordernborrow', '0008_rename_food_name_food_name_and_more'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
