# Generated by Django 4.2.6 on 2023-11-29 06:37

from django.db import migrations
from django.core.management import call_command

def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "drink.json")

class Migration(migrations.Migration):

    dependencies = [
        ('ordernborrow', '0010_drink'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
