# Generated by Django 4.2.4 on 2023-10-28 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordernborrow', '0006_remove_borrowedhistory_borrowed'),
        ('trackernplanner', '0002_booktracker_status_booktrackermember_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktrackermember',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordernborrow.borrowedbook'),
        ),
    ]
