# Generated by Django 4.2.4 on 2023-10-29 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0002_auto_20231021_1353'),
        ('trackernplanner', '0003_alter_booktrackermember_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktrackermember',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booklist.buku'),
        ),
    ]
