# Generated by Django 4.2.4 on 2023-10-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackernplanner', '0006_alter_booktrackermember_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookPlanner',
        ),
    ]
