# Generated by Django 4.2.4 on 2023-12-15 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trackernplanner', '0007_delete_bookplanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktracker',
            name='tracked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
