# Generated by Django 4.2.6 on 2023-10-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewmodul', '0002_jumlahreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumlahreview',
            name='jumlah',
            field=models.IntegerField(default=0),
        ),
    ]
