# Generated by Django 4.2.6 on 2023-10-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewmodul', '0002_reviewmember_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmember',
            old_name='username',
            new_name='name',
        ),
    ]
