# Generated by Django 4.2.6 on 2023-10-26 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewmodul', '0003_rename_username_reviewmember_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmember',
            old_name='name',
            new_name='username',
        ),
    ]
