# Generated by Django 4.2.6 on 2023-10-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewmodul', '0007_reviewonce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewonce',
            old_name='done_review',
            new_name='done',
        ),
        migrations.RenameField(
            model_name='reviewonce',
            old_name='review_history',
            new_name='revhistory',
        ),
    ]
