# Generated by Django 4.2.6 on 2023-10-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewmodul', '0008_rename_done_review_reviewonce_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumlahreview',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ReviewOnce',
        ),
    ]
