# Generated by Django 4.2.6 on 2023-10-29 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0002_auto_20231021_1353'),
        ('reviewmodul', '0010_remove_jumlahreview_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booklist.buku')),
                ('reviewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewmodul.reviewmember')),
            ],
        ),
    ]
