# Generated by Django 4.2.6 on 2023-10-29 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviewmodul', '0011_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewed',
            name='reviewed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
