# Generated by Django 4.2.6 on 2023-10-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewmodul', '0014_reviewed_book_alter_reviewed_reviewed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviewed',
        ),
    ]
