# Generated by Django 4.2.6 on 2023-10-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gambar', models.CharField(max_length=255)),
                ('Judul', models.CharField(max_length=255)),
                ('Penulis', models.CharField(max_length=255)),
                ('Kategori', models.CharField(max_length=255)),
                ('Rating', models.IntegerField()),
            ],
        ),
    ]
