# Generated by Django 4.2.6 on 2023-10-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbuku',
            name='Status',
            field=models.CharField(default='Waiting For Approval', max_length=255),
        ),
    ]
